/*  tasks  */
export const STARTED_FETCH_TASKS = 'STARTED_FETCH_TASKS';
export const FINISHED_FETCH_TASKS = 'FINISHED_FETCH_TASKS';
export const ERROR_FETCH_TASKS = 'ERROR_FETCH_TASKS';

/**/
export const STARTED_CREATE_TASK = 'STARTED_CREATE_TASK';
export const FINISHED_CREATE_TASK = 'FINISHED_CREATE_TASK';
export const ERROR_CREATE_TASK = 'ERROR_CREATE_TASK';
