/*  tasks  */
export const STARTED_FETCH_TASKS = 'STARTED_FETCH_TASKS';
export const FINISHED_FETCH_TASKS = 'FINISHED_FETCH_TASKS';
export const ERROR_FETCH_TASKS = 'ERROR_FETCH_TASKS';

/* create tasks*/
export const STARTED_CREATE_TASK = 'STARTED_CREATE_TASK';
export const FINISHED_CREATE_TASK = 'FINISHED_CREATE_TASK';
export const ERROR_CREATE_TASK = 'ERROR_CREATE_TASK';

/* update tasks*/
export const STARTED_UPDATE_TASK = 'STARTED_UPDATE_TASK';
export const FINISHED_UPDATE_TASK = 'FINISHED_UPDATE_TASK';
export const ERROR_UPDATE_TASK = 'ERROR_UPDATE_TASK';

/* remove user */
export const STARTED_REMOVE_USER_TASK = 'STARTED_REMOVE_USER_TASK';
export const FINISHED_REMOVE_USER_TASK = 'FINISHED_REMOVE_USER_TASK';
export const ERROR_REMOVE_USER_TASK = 'ERROR_REMOVE_USER_TASK';
